package com.auth.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.time.LocalDateTime;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "email_verifications")
public class EmailVerification {
    @Id
    private String email;
    private String fullName;
    private String contact;
    private LocalDate dob;
    private String otp;
    private LocalDateTime otpExpiryTime;

    // All getters and setters are automatically generated by Lombok @Data annotation:
    // getEmail()
    // getFullName()
    // getContact()
    // getDob()
    // getOtp()
    // getOtpExpiryTime()
    // setEmail()
    // setFullName()
    // setContact()
    // setDob()
    // setOtp()
    // setOtpExpiryTime()
}